---
abstract: 'L<Pod::Coverage> extension for L<Moose>'
author:
  - "Robert 'phaylon' Sedlacek <rs@474.at>"
build_requires:
  FindBin: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Coverage-Moose
no_index:
  directory:
    - inc
    - t
provides:
  Pod::Coverage::Moose:
    file: lib/Pod/Coverage/Moose.pm
    version: 0.04
requires:
  Carp: 0
  Class::MOP: 0
  Moose: 0.24
  Perl6::Junction: 0
  Pod::Coverage: 0
  namespace::clean: 0.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
